[package]
name = "rock-paper-scissors"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simurgh-core = { path = "../../simurgh-core" }

rand = "0.8.4"
blarg = "1.0.3"
